# Generated by Django 5.1.1 on 2025-11-30 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plant", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="plant",
            name="address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
