# Generated by Django 5.1.1 on 2025-11-30 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("plant", "0002_plant_address"),
    ]

    operations = [
        migrations.RenameField(
            model_name="plant",
            old_name="address",
            new_name="cep",
        ),
    ]
