# Generated by Django 5.1.1 on 2025-11-30 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plant", "0003_rename_address_plant_cep"),
    ]

    operations = [
        migrations.AddField(
            model_name="plant",
            name="number",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
